OPL-64: New calcrule - Unconditional cash payment
openimis/openimis-be-calcrule_unconditional_cash_payment_py pull request #1
Opened 2022-03-28 14:21 UTC by wzglinieckisoldevelo

https://openimis.atlassian.net/browse/OPL-64

New calcrule - unconditional cash payment

2022-03-28 14:35 UTC, sniedzielski commented on calcrule_unconditional_cash_payment/calculation_rule.py
> +               and context in ["policyCreated"] \
@wzglinieckisoldevelo Please replace 'policyCreated' into 'PolicyCreated'

2022-03-28 14:36 UTC, sniedzielski commented on calcrule_unconditional_cash_payment/calculation_rule.py
> +                cls.run_convert(instance=instance, context=context, convert_to='Bill', payment_plan=payment_plan,
@wzglinieckisoldevelo Please write this in such way as below:
`run_convert(
    instance=instance, 
   context=context, 
   convert_to='Bill', 
   payment_plan=payment_plan,
)
`

2022-03-28 14:39 UTC, sniedzielski commented on calcrule_unconditional_cash_payment/calculation_rule.py
> +            return "conversion finished " + cls.calculation_rule_name
@wzglinieckisoldevelo Please use F string

2022-03-28 14:41 UTC, sniedzielski commented on calcrule_unconditional_cash_payment/calculation_rule.py
> +            if 'calculation_rule' in payment_plan.json_ext:
@wzglinieckisoldevelo Please move 'obtaining values from json_ext' logic into separate private method. You can also as you wish move this into 'utils'.

2022-03-28 14:41 UTC, sniedzielski commented on calcrule_unconditional_cash_payment/calculation_rule.py
> +            if convert_to == 'Bill':
@wzglinieckisoldevelo You can also move this part into separate method.

2022-03-28 14:43 UTC, sniedzielski commented on calcrule_unconditional_cash_payment/calculation_rule.py
> +        if context == "policyCreated":
@wzglinieckisoldevelo Please replace 'policyCreated' into 'PolicyCreated'

2022-03-28 14:49 UTC, sniedzielski commented on calcrule_unconditional_cash_payment/calculation_rule.py
> +                convert_results['bill_data_line'] = [PolicyToBillItemConverter.to_bill_item_obj(instance,
@wzglinieckisoldevelo same as above

2022-03-28 14:50 UTC, sniedzielski requested changes
@wzglinieckisoldevelo Good job. Please refer to the comments. Mainly code aesthetics,

2022-03-29 07:13 UTC, sniedzielski commented on calcrule_unconditional_cash_payment/converters/policy_to_bill.py
> +
@wzglinieckisoldevelo What about 'unit_price'?

2022-03-29 08:17 UTC, wzglinieckisoldevelo commented
I've implemented those fixes as requested,

2022-03-29 08:18 UTC, sniedzielski approved these changes
@wzglinieckisoldevelo thx for improving solution! Good job!

2022-03-31 10:11 UTC, sniedzielski commented
@delcroip @wzglinieckisoldevelo ok. We can add later simple test cases (unit tests): 
- test conversion from Policy to Bill json
- test calculating amount (check if proper value is taken from json_ext PaymentPlan (lumpsum_to_be_paid))

2022-04-04 10:17 UTC, merged